### ISSUE TITLE
data-precess数据预处理

### ISSUE THREAD

**Issue by nicegdhj** [RosenX/PopularMusicPrediction#1]
请问下， data-precess.py这个文件并不在 仓库里面 请问下是忘了上传还是写到了其他的文件操作当中了？我对于那个时间格式的处理有点疑惑...谢谢

更新：
抱歉，我发现我搞错题目了，我指的是Ali-moblie那道题...我在里面找到了 感谢

**Comment by Shanshi66** [comment]
:)
